apiVersion: apps/v1
kind: Deployment
metadata:
  name: stateless-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stateless-app
  template:
    metadata:
      labels:
        app: stateless-app
    spec:
      containers:
        - name: stateless-app
          image: registry.local/stateless-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: env-volume
              mountPath: /var/www/private/app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: env-volume
          secret:
            secretName: app-secret
